version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erp_webhook_go
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=erpJavaGoTrips

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: erp_swagger
    ports:
      - "8082:8080"
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/openapi.yaml:ro
