openapi: 3.0.3
info:
  title: API de Assignments
  description: Endpoint para notificação de atribuições de motoristas
  version: "1.0.0"
paths:
  /v1/assignments/notify:
    post:
      summary: Notifica uma atribuição de motorista
      description: Recebe informações de atribuição e processa a notificação.
      operationId: notifyAssignment
      tags:
        - assignments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - driver_id
                - route
              properties:
                driver_id:
                  type: string
                  description: ID do motorista
                route:
                  type: string
                  description: Descrição da rota
      responses:
        '202':
          description: Requisição aceita e processada
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '401':
          description: Não autorizado
        '422':
          description: Entidade não processável (motorista não encontrado)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '500':
          description: Erro interno do servidor